### ISSUE TITLE
Structure of incept page for syllabus so that both web page and syllabus can be smoothly scrollable.

### ISSUE THREAD

**Issue by trmofsln** [JK-Open-Source-Community/JKOSC#21]
### Structure of syllabus part in Incept page

I think ,there may be two ways for doing the thing-

* First is the way of loading pdf file into page and adding a section (separate)(not on full width , because if we give it in full width, then we will only able to scroll the pdf , not the web page , we will only able to scroll page once the scroll pdf part will get over., so i think we should choose separate section for pdf loading).
 It may be look like this 

![Untitled](https://user-images.githubusercontent.com/53634176/117611571-59c65600-b181-11eb-9308-ef14ae8c2307.png)

or you may also suggest some changes in design. 

* second way is to not load pdf , all the syllabus part would be well documented in real text just like as a article. then of course there would not be any issue regarding the smooth scrolling of page. 
It would be like this-

![Untitled1](https://user-images.githubusercontent.com/53634176/117612045-2b954600-b182-11eb-915a-87f80c1d8d9a.png)

Please suggest your opinion, that what would be better here?
You can also suggest if any other way also possible for doing the same. 
Your suggestion are needed for us to further continue in this domain.

**Comment by ayushagarwal210** [comment]
I think the second option is better ,in this we can provide textbooks and videos by adding links to the headings.

**Comment by harekrishnarai** [comment]
Yes, That seems to be perfect.

**Comment by two-ticks** [comment]
@abhishek-ch88  can you work on this  issue with @trmofsln  ?
